package service

import (
	"testing"
	"time"

	netbootV1 "github.com/go-tangra/go-tangra-netboot/gen/go/netboot/service/v1"
	"github.com/go-tangra/go-tangra-netboot/internal/netbootd"
)

// An upstream value this module does not know about must land on the
// UNSPECIFIED zero value rather than being mistaken for a known state.
func TestEnumLookupIsTolerant(t *testing.T) {
	tests := []struct {
		raw  string
		want netbootV1.ProvisionState
	}{
		{"installing", netbootV1.ProvisionState_PROVISION_STATE_INSTALLING},
		{"INSTALLING", netbootV1.ProvisionState_PROVISION_STATE_INSTALLING},
		{"  installed  ", netbootV1.ProvisionState_PROVISION_STATE_INSTALLED},
		{"", netbootV1.ProvisionState_PROVISION_STATE_UNSPECIFIED},
		{"quantum-entangled", netbootV1.ProvisionState_PROVISION_STATE_UNSPECIFIED},
	}
	for _, tt := range tests {
		t.Run("raw="+tt.raw, func(t *testing.T) {
			if got := lookup(provisionStateToProto, tt.raw); got != tt.want {
				t.Errorf("lookup(%q) = %v, want %v", tt.raw, got, tt.want)
			}
		})
	}
}

// The reverse tables are generated by inverting the forward ones, so a
// round trip must be lossless for every declared value.
func TestEnumTablesRoundTrip(t *testing.T) {
	for raw, enum := range provisionStateToProto {
		if got := provisionStateToUpstream[enum]; got != raw {
			t.Errorf("provisionState %q -> %v -> %q, want %q", raw, enum, got, raw)
		}
	}
	for raw, enum := range firmwareToProto {
		if got := firmwareToUpstream[enum]; got != raw {
			t.Errorf("firmware %q -> %v -> %q, want %q", raw, enum, got, raw)
		}
	}
	for raw, enum := range sessionStateToProto {
		if got := sessionStateToUpstream[enum]; got != raw {
			t.Errorf("sessionState %q -> %v -> %q, want %q", raw, enum, got, raw)
		}
	}
}

// The UNSPECIFIED enum must map back to the empty string, so an unset filter
// is omitted from the upstream query rather than sent as a literal.
func TestUnspecifiedEnumMapsToEmptyFilter(t *testing.T) {
	if got := provisionStateToUpstream[netbootV1.ProvisionState_PROVISION_STATE_UNSPECIFIED]; got != "" {
		t.Errorf("unspecified provision state = %q, want an empty filter", got)
	}
	if got := sessionStateToUpstream[netbootV1.SessionState_SESSION_STATE_UNSPECIFIED]; got != "" {
		t.Errorf("unspecified session state = %q, want an empty filter", got)
	}
}

func TestNilInputsMapToNil(t *testing.T) {
	if got := toMachine(nil); got != nil {
		t.Errorf("toMachine(nil) = %v, want nil", got)
	}
	if got := toProfile(nil); got != nil {
		t.Errorf("toProfile(nil) = %v, want nil", got)
	}
	if got := toSession(nil); got != nil {
		t.Errorf("toSession(nil) = %v, want nil", got)
	}
	if got := toArtifact(nil); got != nil {
		t.Errorf("toArtifact(nil) = %v, want nil", got)
	}
	if got := toDhcpConfig(nil); got != nil {
		t.Errorf("toDhcpConfig(nil) = %v, want nil", got)
	}
	if got := toInstallNetwork(nil); got != nil {
		t.Errorf("toInstallNetwork(nil) = %v, want nil", got)
	}
	if got := fromInstallNetwork(nil); got != nil {
		t.Errorf("fromInstallNetwork(nil) = %v, want nil", got)
	}
	if got := fromProfileInput(nil); got != nil {
		t.Errorf("fromProfileInput(nil) = %v, want nil", got)
	}
}

// A nil element inside an upstream list must be dropped, not turned into a
// zero-valued entry that a UI would render as a blank row.
func TestSliceMappersSkipNilElements(t *testing.T) {
	if got := toMachines([]*netbootd.Machine{nil, {ID: "m-1"}, nil}); len(got) != 1 {
		t.Errorf("toMachines() returned %d entries, want 1", len(got))
	}
	if got := toProfiles([]*netbootd.Profile{nil, {ID: "p-1"}}); len(got) != 1 {
		t.Errorf("toProfiles() returned %d entries, want 1", len(got))
	}
	if got := toSessions([]*netbootd.ProvisioningSession{nil}); len(got) != 0 {
		t.Errorf("toSessions() returned %d entries, want 0", len(got))
	}
	if got := toArtifacts([]*netbootd.BootArtifact{nil}); len(got) != 0 {
		t.Errorf("toArtifacts() returned %d entries, want 0", len(got))
	}
	if got := toLeases([]*netbootd.Lease{nil}); len(got) != 0 {
		t.Errorf("toLeases() returned %d entries, want 0", len(got))
	}
	if got := toForeignServers([]*netbootd.ForeignServer{nil}); len(got) != 0 {
		t.Errorf("toForeignServers() returned %d entries, want 0", len(got))
	}
	if got := toUnknownBoots([]*netbootd.UnknownBoot{nil}); len(got) != 0 {
		t.Errorf("toUnknownBoots() returned %d entries, want 0", len(got))
	}
	if got := toEvents([]*netbootd.ProvisioningEvent{nil}); len(got) != 0 {
		t.Errorf("toEvents() returned %d entries, want 0", len(got))
	}
	if got := toTransfers([]*netbootd.Transfer{nil}); len(got) != 0 {
		t.Errorf("toTransfers() returned %d entries, want 0", len(got))
	}
	if got := toDhcpSubnets([]*netbootd.DhcpSubnet{nil}); len(got) != 0 {
		t.Errorf("toDhcpSubnets() returned %d entries, want 0", len(got))
	}
	if got := fromDhcpSubnets([]*netbootV1.DhcpSubnet{nil}); len(got) != 0 {
		t.Errorf("fromDhcpSubnets() returned %d entries, want 0", len(got))
	}
}

func TestToTimestamp(t *testing.T) {
	if got := toTimestamp(netbootd.Timestamp{}); got != nil {
		t.Errorf("toTimestamp(zero) = %v, want nil", got)
	}
	moment := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	got := toTimestamp(netbootd.Timestamp{Time: moment})
	if got == nil {
		t.Fatal("toTimestamp(set) = nil, want a timestamp")
	}
	if !got.AsTime().Equal(moment) {
		t.Errorf("toTimestamp() = %v, want %v", got.AsTime(), moment)
	}
}

func TestToPageMetaHandlesNil(t *testing.T) {
	got := toPageMeta(nil)
	if got == nil {
		t.Fatal("toPageMeta(nil) = nil, want an empty meta rather than a nil message")
	}
	if got.GetTotal() != 0 {
		t.Errorf("total = %d, want 0", got.GetTotal())
	}
}

func TestToPage(t *testing.T) {
	if got := toPage(nil); got != (netbootd.Page{}) {
		t.Errorf("toPage(nil) = %+v, want the zero page", got)
	}
	got := toPage(&netbootV1.PageRequest{Page: ptr(uint32(3)), PageSize: ptr(uint32(25))})
	if got.Page != 3 || got.PageSize != 25 {
		t.Errorf("toPage() = %+v, want {3 25}", got)
	}
}

// The JSON null literal is collapsed so clients need not special-case it.
func TestRawJSONString(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{"null", ""},
		{"", ""},
		{`{"a":1}`, `{"a":1}`},
	}
	for _, tt := range tests {
		if got := rawJSONString([]byte(tt.in)); got != tt.want {
			t.Errorf("rawJSONString(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestNormaliseMAC(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{"AA:BB:CC:DD:EE:FF", "aa:bb:cc:dd:ee:ff"},
		{"aa-bb-cc-dd-ee-ff", "aa:bb:cc:dd:ee:ff"},
		{"  aa:bb:cc:dd:ee:ff  ", "aa:bb:cc:dd:ee:ff"},
		// Unparseable input is passed through so the upstream renders the
		// verdict rather than this module silently substituting a value.
		{"not-a-mac", "not-a-mac"},
		{"", ""},
	}
	for _, tt := range tests {
		t.Run("in="+tt.in, func(t *testing.T) {
			if got := normaliseMAC(tt.in); got != tt.want {
				t.Errorf("normaliseMAC(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

// The password must move into a Secret at the boundary, so nothing
// downstream holds it as a bare string.
func TestFromProfileInputWrapsThePassword(t *testing.T) {
	body := fromProfileInput(&netbootV1.ProfileInput{
		Name: "p", UbuntuRelease: "noble", Password: "plaintext",
	})
	if body.Password.Reveal() != "plaintext" {
		t.Errorf("Password = %q, want the plaintext preserved for the upstream", body.Password.Reveal())
	}
	if rendered := body.Password.String(); rendered == "plaintext" {
		t.Error("Password renders as plaintext, want it redacted")
	}
}
