// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-netboot/internal/authz"
	"github.com/go-tangra/go-tangra-netboot/internal/cert"
	"github.com/go-tangra/go-tangra-netboot/internal/data"
	"github.com/go-tangra/go-tangra-netboot/internal/metrics"
	"github.com/go-tangra/go-tangra-netboot/internal/server"
	"github.com/go-tangra/go-tangra-netboot/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	config, err := data.NewNetbootdConfig(context)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := data.NewNetbootdClient(context, config)
	if err != nil {
		return nil, nil, err
	}
	checker := authz.NewChecker()
	machineService := service.NewMachineService(context, client, checker, collector)
	profileService := service.NewProfileService(context, client, checker, collector)
	dhcpService := service.NewDhcpService(context, client, checker, collector)
	sessionService := service.NewSessionService(context, client, checker, collector)
	artifactService := service.NewArtifactService(context, client, checker, collector)
	systemService := service.NewSystemService(context, client, checker, collector)
	grpcServer := server.NewGRPCServer(context, certManager, collector, machineService, profileService, dhcpService, sessionService, artifactService, systemService)
	httpServer := server.NewHTTPServer(context)
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
